# This configurations are prone to change
# This configurations are not final yet
services:
  # postgresql for relational database
  postgres:
    image: postgres:latest
    container_name: zora_postgres
    restart: no # for development, no need to auto restart
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # redis for caching
  redis:
    image: redis/redis-stack:latest
    container_name: zora_redis
    restart: no # for development, no need to auto restart
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
  # rabbitmq for message broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: zora_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  # pinecone for vector database
  index1:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    environment:
      PORT: 5080
      INDEX_TYPE: serverless
      DIMENSION: 2 
      METRIC: cosine
    ports:
      - 5081:5081
    platform: linux/amd64

# volumes for docker image
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data: